#!/usr/bin/env python3
"""Merge GitHub repositories into this repository and prepare a GitHub Pages site."""

from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_MERGE_ROOT = Path("merged_repositories")
AUTO_BRANCH = "auto"


def run_command(command: list[str], cwd: Path | None = None) -> subprocess.CompletedProcess:
    return subprocess.run(
        command,
        cwd=str(cwd) if cwd else None,
        check=True,
        text=True,
        capture_output=True,
    )


def list_repositories(owner: str) -> list[str]:
    result = run_command(
        [
            "gh",
            "repo",
            "list",
            owner,
            "--limit",
            "1000",
            "--json",
            "name",
        ]
    )
    payload = json.loads(result.stdout)
    return sorted(item["name"] for item in payload)


def remote_exists(remote_name: str) -> bool:
    result = run_command(["git", "remote"], cwd=ROOT)
    remotes = [line.strip() for line in result.stdout.splitlines() if line.strip()]
    return remote_name in remotes


def detect_default_branch(remote_url: str) -> str:
    result = run_command(["git", "ls-remote", "--symref", remote_url, "HEAD"], cwd=ROOT)
    for line in result.stdout.splitlines():
        if line.startswith("ref:") and "\tHEAD" in line:
            ref = line.split()[1]
            return ref.rsplit("/", maxsplit=1)[-1]
    raise RuntimeError(f"Unable to determine default branch for {remote_url}")


def merge_repository(owner: str, repository: str, merge_root: Path, requested_branch: str, squash: bool) -> str:
    remote_name = f"merge-{repository}"
    remote_url = f"https://github.com/{owner}/{repository}.git"
    destination = merge_root / repository

    if remote_exists(remote_name):
        run_command(["git", "remote", "remove", remote_name], cwd=ROOT)

    selected_branch = detect_default_branch(remote_url) if requested_branch == AUTO_BRANCH else requested_branch

    run_command(["git", "remote", "add", remote_name, remote_url], cwd=ROOT)
    run_command(["git", "fetch", remote_name], cwd=ROOT)

    subtree_command = ["git", "subtree", "add", f"--prefix={destination.as_posix()}", remote_name, selected_branch]
    if (ROOT / destination).exists():
        subtree_command[2] = "pull"
    if squash:
        subtree_command.append("--squash")

    try:
        run_command(subtree_command, cwd=ROOT)
    finally:
        run_command(["git", "remote", "remove", remote_name], cwd=ROOT)

    return selected_branch


def write_live_index(owner: str, repositories: list[str], merge_root: Path) -> Path:
    docs_dir = ROOT / "docs"
    docs_dir.mkdir(parents=True, exist_ok=True)
    index_path = docs_dir / "index.html"

    links = "\n".join(
        f'<li><a href="../{(merge_root / repo).as_posix()}/">{owner}/{repo}</a></li>' for repo in repositories
    )

    html = f"""<!doctype html>
<html lang=\"en\">
  <head>
    <meta charset=\"utf-8\" />
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />
    <title>Merged GitHub Repositories</title>
    <style>
      body {{ font-family: Arial, sans-serif; margin: 2rem; line-height: 1.5; }}
      h1 {{ margin-bottom: 0.5rem; }}
    </style>
  </head>
  <body>
    <h1>Merged Repositories for {owner}</h1>
    <p>Generated by <code>focus_ai/scripts/merge_github_repositories.py</code>.</p>
    <ul>
      {links}
    </ul>
  </body>
</html>
"""
    index_path.write_text(html, encoding="utf-8")
    return index_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Merge GitHub repositories and prepare a live index page.")
    parser.add_argument("--owner", required=True, help="GitHub user or organization name.")
    parser.add_argument(
        "--repos",
        nargs="*",
        help="Optional explicit repository names. If omitted, repositories are listed with gh CLI.",
    )
    parser.add_argument(
        "--default-branch",
        default=AUTO_BRANCH,
        help="Branch name used with git subtree. Use 'auto' to detect each repository default branch.",
    )
    parser.add_argument(
        "--merge-root",
        default=DEFAULT_MERGE_ROOT.as_posix(),
        help="Directory where repositories are merged (default: merged_repositories).",
    )
    parser.add_argument(
        "--squash",
        action="store_true",
        help="Use --squash while adding/pulling git subtree histories.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print repositories that would be merged without changing git history.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    merge_root = Path(args.merge_root)
    repositories = sorted(args.repos) if args.repos else list_repositories(args.owner)

    if not repositories:
        raise SystemExit("No repositories found to merge.")

    if args.dry_run:
        print("Dry run. Repositories that would be merged:")
        for repo in repositories:
            print(f"- {args.owner}/{repo}")
        return

    for repository in repositories:
        print(f"Merging {args.owner}/{repository} into {merge_root / repository}")
        branch = merge_repository(args.owner, repository, merge_root, args.default_branch, args.squash)
        print(f"  -> using branch: {branch}")

    index_path = write_live_index(args.owner, repositories, merge_root)
    print(f"Live index written to {index_path}")
    print("Next: push this branch and enable GitHub Pages from the docs/ directory.")


if __name__ == "__main__":
    main()
